name: Auto Subscribe
 
# 定时执行，每天 8 点
on:
  schedule:
    - cron: "0 8 * * *" 
  workflow_dispatch:  # 允许手动触发

jobs:
  subscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run script
        run: node main.js

      - name: Commit subscribe link
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add subscribe_url.txt
          git commit -m "Update subscribe link $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
