name: Auto Register & Update Subscription

on:
  schedule:
    - cron: "0 */3 * * *"   # ✅ 每3小时运行一次
  workflow_dispatch:        # 手动运行也支持

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # ✅ 拉取完整历史，防止 push 冲突

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run Register Script
      run: |
        echo "▶ 运行 Scriptable 注册脚本..."
        node "main.js" > subscribe_url.txt
        echo "✅ 注册完成，以下为订阅链接："
        cat subscribe_url.txt

    - name: Download Subscription File
      run: |
        echo "▶ 正在下载订阅文件..."
        URL=$(cat subscribe_url.txt)
        if [ -z "$URL" ]; then
          echo "❌ 未获取到订阅链接"
          exit 1
        fi
        curl -sL "$URL" -o subscribe.txt
        echo "✅ 已保存为 subscribe.txt"

    - name: Commit & Push Changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "▶ 提交更新..."
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git pull origin main --rebase  # ✅ 拉取远程最新版本，防止冲突
        git add subscribe.txt
        git commit -m "Auto update subscribe $(date +'%Y-%m-%d %H:%M:%S')" || echo "⚠️ 没有变化"
        git push "https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git"
        echo "✅ 推送完成"
