name: Sort & Commit

on:
  push:
    paths: ['luanxu.txt']   # 仅当 luanxu.txt 变动才触发
  workflow_dispatch:        # 手动按钮

jobs:
  sort:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run sort
        run: python sort.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dy.txt
          git diff --cached --quiet || (git commit -m "Auto-sort luanxu.txt → dy.txt" && git push)
