name: 真实代理测速
on:
  workflow_dispatch:   # 手动按钮
  push:
    paths:
      - 'yuanshi_raw.txt'

jobs:
  speed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: 安装 sing-box（静态编译，含 convert）
        run: |
          # 下载自带 convert 的静态二进制（国内镜像，保证存在）
          curl -L -o sing-box https://github.com/wgetnz/sing-box-speed/releases/download/v0.1.1/sing-box_1.9.0_linux_amd64
          chmod +x sing-box && sudo mv sing-box /usr/local/bin
          sudo apt-get update && sudo apt-get install -y obfs4proxy
          /usr/local/bin/sing-box version
          /usr/local/bin/sing-box convert --help > /dev/null && echo "convert 可用"




      - name: 运行真实代理测速
        run: |
          chmod +x speed.py
          python3 speed.py

      - name: 提交结果
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add speedpaixu.txt
          git commit -m "bot: 真实代理测速完成" && git push || echo "无变化"