name: 真实代理测速
on:
  workflow_dispatch:   # 手动按钮
  push:
    paths:
      - 'yuanshi_raw.txt'

jobs:
  speed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 安装 sing-box（开发版，含 convert）
        run: |
          # 下载开发版（带 convert）
          curl -L -o sb.tgz https://github.com/SagerNet/sing-box/releases/download/v1.9.0-rc.1/sing-box-1.9.0-rc.1-linux-amd64.tar.gz
          tar -xzf sb.tgz && sudo mv sing-box-*/sing-box /usr/local/bin && rm -rf sb.tgz sing-box-*
          sudo apt-get update && sudo apt-get install -y obfs4proxy
          sing-box version
          sing-box convert --help > /dev/null && echo "convert 可用"


      - name: 运行真实代理测速
        run: |
          chmod +x speed.py
          python3 speed.py

      - name: 提交结果
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add speedpaixu.txt
          git commit -m "bot: 真实代理测速完成" && git push || echo "无变化"
