name: speed按钮测试
on:
  workflow_dispatch:

jobs:
  speed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
			      - name: 运行测速
        run: |
          chmod +x speed.py
          python3 speed.py