name: 终极测速

on:
  workflow_dispatch:

jobs:
  speed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 运行 speed.py 测速
        run: |
          chmod +x speed.py
          python3 speed.py

      - name: 提交结果
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add speedpaixu.txt
          git commit -m "bot: 终极测速完成" && git push || echo "无变化"
